version: '3'

services:

  clickhouse-01:
    image: altinity/clickhouse-server:22.3.8.40.altinitystable
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - 9001:9000
      - 8123:8123
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./logs_1:/var/log/clickhouse-server
      - ./data/server-01:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

